import { Octokit } from '@octokit/rest';
import yaml from 'js-yaml';

export interface GitHubWorkflowResult {
  success: boolean;
  path?: string;
  sha?: string;
  error?: string;
  prUrl?: string;
  prNumber?: number;
  branch?: string;
}

export interface WorkflowContent {
  yaml: string;
  metadata: {
    path: string;
    sha: string;
    lastModified: string;
  };
}

export class GitHubWorkflowManager {
  private octokit: Octokit;
  private owner = 'mediar-ai';
  private repo = 'workflows';
  private baseBranch = 'main';

  constructor() {
    const token = process.env.GITHUB_WORKFLOW_TOKEN || process.env.GITHUB_TOKEN;
    if (!token) {
      console.warn('GitHub token not configured - GitHub operations will fail');
    }
    this.octokit = new Octokit({
      auth: token,
      userAgent: 'mediar-workflow-manager'
    });
  }

  /**
   * Save workflow to GitHub repository (creates branch and PR)
   */
  async saveWorkflow(
    workflowName: string,
    yamlContent: string,
    category: 'production' | 'development' | 'archived' = 'production',
    message?: string,
    createPR: boolean = true
  ): Promise<GitHubWorkflowResult> {
    try {
      // Validate YAML
      yaml.load(yamlContent);

      // Prepare path and branch name
      const sanitizedName = workflowName.toLowerCase().replace(/[^a-z0-9-_]/g, '_');
      const filePath = `${category}/${sanitizedName}/workflow.yaml`;
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
      const branchName = `workflow/${sanitizedName}-${timestamp}`;

      if (createPR) {
        // Create a new branch from main
        const { data: mainRef } = await this.octokit.git.getRef({
          owner: this.owner,
          repo: this.repo,
          ref: `heads/${this.baseBranch}`
        });

        await this.octokit.git.createRef({
          owner: this.owner,
          repo: this.repo,
          ref: `refs/heads/${branchName}`,
          sha: mainRef.object.sha
        });

        console.log(`Created branch: ${branchName}`);
      }

      // Check if file exists on target branch
      let existingSha: string | undefined;
      try {
        const { data: existingFile } = await this.octokit.repos.getContent({
          owner: this.owner,
          repo: this.repo,
          path: filePath,
          ref: createPR ? branchName : this.baseBranch
        });

        if ('sha' in existingFile) {
          existingSha = existingFile.sha;
        }
      } catch (error: any) {
        if (error.status !== 404) {
          throw error;
        }
        // File doesn't exist, will create new
      }

      // Create or update file on the branch
      const { data } = await this.octokit.repos.createOrUpdateFileContents({
        owner: this.owner,
        repo: this.repo,
        path: filePath,
        message: message || `Add/Update workflow: ${workflowName}`,
        content: Buffer.from(yamlContent).toString('base64'),
        branch: createPR ? branchName : this.baseBranch,
        ...(existingSha && { sha: existingSha })
      });

      // Create PR if requested
      if (createPR) {
        const prBody = `## New Workflow: ${workflowName}

### Details
- **Category**: ${category}
- **Path**: \`${filePath}\`
- **Created**: ${new Date().toISOString()}

### Description
${message || 'Workflow created via Mediar UI'}

---
*This PR was automatically generated by the Mediar workflow system*`;

        const { data: pr } = await this.octokit.pulls.create({
          owner: this.owner,
          repo: this.repo,
          title: `Add workflow: ${workflowName}`,
          head: branchName,
          base: this.baseBranch,
          body: prBody
        });

        console.log(`Created PR #${pr.number}: ${pr.html_url}`);

        return {
          success: true,
          path: filePath,
          sha: data.commit.sha,
          prUrl: pr.html_url,
          prNumber: pr.number,
          branch: branchName
        };
      }

      return {
        success: true,
        path: filePath,
        sha: data.commit.sha
      };
    } catch (error) {
      console.error('Error saving workflow to GitHub:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to save workflow'
      };
    }
  }

  /**
   * Get workflow from GitHub repository
   */
  async getWorkflow(
    githubPath: string,
    ref?: string
  ): Promise<WorkflowContent | null> {
    try {
      const { data } = await this.octokit.repos.getContent({
        owner: this.owner,
        repo: this.repo,
        path: githubPath,
        ref: ref || this.baseBranch
      });

      if ('content' in data && data.type === 'file') {
        const yamlContent = Buffer.from(data.content, 'base64').toString('utf-8');

        return {
          yaml: yamlContent,
          metadata: {
            path: data.path,
            sha: data.sha,
            lastModified: new Date().toISOString()
          }
        };
      }

      return null;
    } catch (error: any) {
      if (error.status === 404) {
        console.log(`Workflow not found at path: ${githubPath}`);
        return null;
      }
      console.error('Error fetching workflow from GitHub:', error);
      return null;
    }
  }

  /**
   * List all workflows in a category
   */
  async listWorkflows(category: 'production' | 'development' | 'archived' = 'production') {
    try {
      const { data } = await this.octokit.repos.getContent({
        owner: this.owner,
        repo: this.repo,
        path: category,
        ref: this.baseBranch
      });

      if (!Array.isArray(data)) {
        return [];
      }

      return data
        .filter(item => item.type === 'dir')
        .map(item => ({
          name: item.name,
          path: item.path
        }));
    } catch (error: any) {
      if (error.status === 404) {
        console.log(`Category not found: ${category}`);
        return [];
      }
      console.error('Error listing workflows:', error);
      return [];
    }
  }

  /**
   * Get workflow with associated files
   */
  async getWorkflowWithFiles(githubPath: string): Promise<{
    workflow: WorkflowContent | null;
    files: Record<string, string>;
  }> {
    try {
      // Get the directory path (remove /workflow.yaml if present)
      const dirPath = githubPath.replace(/\/workflow\.yaml$/, '');

      // Get workflow
      const workflowPath = githubPath.endsWith('.yaml') ? githubPath : `${githubPath}/workflow.yaml`;
      const workflow = await this.getWorkflow(workflowPath);

      if (!workflow) {
        return { workflow: null, files: {} };
      }

      // List all files in the directory
      const { data } = await this.octokit.repos.getContent({
        owner: this.owner,
        repo: this.repo,
        path: dirPath,
        ref: this.baseBranch
      });

      const files: Record<string, string> = {};

      if (Array.isArray(data)) {
        for (const item of data) {
          if (item.type === 'file' && !item.name.endsWith('.yaml')) {
            const { data: fileData } = await this.octokit.repos.getContent({
              owner: this.owner,
              repo: this.repo,
              path: item.path,
              ref: this.baseBranch
            });

            if ('content' in fileData) {
              files[item.name] = Buffer.from(fileData.content, 'base64').toString('utf-8');
            }
          }
        }
      }

      return { workflow, files };
    } catch (error) {
      console.error('Error fetching workflow with files:', error);
      return { workflow: null, files: {} };
    }
  }

  /**
   * Create a new version tag
   */
  async createVersion(githubPath: string, version: string): Promise<boolean> {
    try {
      // Get latest commit for this file
      const { data: commits } = await this.octokit.repos.listCommits({
        owner: this.owner,
        repo: this.repo,
        path: githubPath,
        per_page: 1
      });

      if (commits.length === 0) {
        console.error('No commits found for path:', githubPath);
        return false;
      }

      const tagName = `${githubPath.replace(/\//g, '-')}-v${version}`;

      // Create tag
      await this.octokit.git.createRef({
        owner: this.owner,
        repo: this.repo,
        ref: `refs/tags/${tagName}`,
        sha: commits[0].sha
      });

      return true;
    } catch (error) {
      console.error('Error creating version tag:', error);
      return false;
    }
  }
}

// Export singleton instance
export const githubWorkflowManager = new GitHubWorkflowManager();