[project]
name = "browser-workflow-capture-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "modal",
    "psycopg2-binary",
    "httpx",
    "websockets",
    "pyyaml>=6.0.2",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
