#!/usr/bin/env node
import dotenv from 'dotenv';
import { createClient } from '@supabase/supabase-js';

dotenv.config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function applyMigration() {
  console.log('Applying GitHub columns migration...\n');

  const migration = `
    -- Add columns for GitHub references if they don't exist
    ALTER TABLE public.deployed_workflows
    ADD COLUMN IF NOT EXISTS github_path text,
    ADD COLUMN IF NOT EXISTS github_ref text DEFAULT 'main',
    ADD COLUMN IF NOT EXISTS github_sha text,
    ADD COLUMN IF NOT EXISTS github_sync_status text DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS github_last_synced_at timestamp with time zone;

    -- Create sync log table if it doesn't exist
    CREATE TABLE IF NOT EXISTS public.github_workflow_sync_log (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        workflow_id bigint,
        operation text NOT NULL,
        github_path text,
        github_sha text,
        status text NOT NULL,
        error_message text,
        created_at timestamp with time zone DEFAULT now(),
        created_by uuid
    );
  `;

  try {
    // Execute migration using RPC or direct query
    console.log('Testing database connection...');
    const { data: test, error: testError } = await supabase
      .from('deployed_workflows')
      .select('id')
      .limit(1);

    if (testError) {
      console.error('Database connection failed:', testError);
      return;
    }

    console.log('✅ Database connection successful');

    // Check if columns already exist
    const { data: columns, error: colError } = await supabase.rpc('get_table_columns', {
      table_name: 'deployed_workflows'
    }).select('*').limit(1);

    if (!colError) {
      console.log('✅ Checking existing columns...');
    }

    // Since we can't run ALTER directly via API, let's check what we have
    const { data: sample, error: sampleError } = await supabase
      .from('deployed_workflows')
      .select('*')
      .limit(1)
      .single();

    if (sample) {
      console.log('\nCurrent deployed_workflows columns:');
      console.log(Object.keys(sample).join(', '));

      if ('github_path' in sample) {
        console.log('\n✅ GitHub columns already exist!');
      } else {
        console.log('\n⚠️ GitHub columns not found. Please run this SQL in Supabase dashboard:');
        console.log('\n' + migration);
      }
    }

  } catch (error) {
    console.error('Error:', error);
  }
}

applyMigration();