#!/usr/bin/env python3
"""
Implement comprehensive workflow versioning system.
This script adds full version control to deployed_workflows with:
- Version history storage
- Rollback capabilities  
- Execution traceability
- Backward compatibility

Usage: python scripts/implement_workflow_versioning.py
"""

import os
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv('.env.local')

def get_db_connection():
    """Get database connection from environment variables"""
    conn_string = os.getenv('SUPABASE_CONN_STRING')
    if not conn_string:
        raise ValueError("SUPABASE_CONN_STRING environment variable not set in .env.local")
    
    conn = psycopg2.connect(conn_string)
    return conn

def check_versions_table_exists(conn):
    """Check if deployed_workflow_versions table already exists."""
    print("🔍 Checking if deployed_workflow_versions table exists...")
    
    with conn.cursor() as cur:
        cur.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'deployed_workflow_versions'
            )
        """)
        result = cur.fetchone()
        return result[0] if result else False

def check_version_tracking_columns_exist(conn):
    """Check if version tracking columns exist in deployed_workflows."""
    print("🔍 Checking if version tracking columns exist...")
    
    with conn.cursor() as cur:
        # Check for current_version_id column
        cur.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'deployed_workflows' 
                AND column_name = 'current_version_id'
            )
        """)
        result1 = cur.fetchone()
        current_version_id_exists = result1[0] if result1 else False
        
        # Check for total_versions column
        cur.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'deployed_workflows' 
                AND column_name = 'total_versions'
            )
        """)
        result2 = cur.fetchone()
        total_versions_exists = result2[0] if result2 else False
        
        return current_version_id_exists, total_versions_exists

def create_workflow_versions_table(conn):
    """Create the deployed_workflow_versions table."""
    print("📝 Creating deployed_workflow_versions table...")
    
    with conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public.deployed_workflow_versions (
                id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                workflow_id bigint NOT NULL REFERENCES public.deployed_workflows(id) ON DELETE CASCADE,
                version_number text NOT NULL,
                automation_sequence jsonb NOT NULL,
                is_active boolean DEFAULT false,
                created_at timestamp with time zone DEFAULT now(),
                created_by text,
                change_notes text,
                CONSTRAINT unique_workflow_version UNIQUE(workflow_id, version_number)
            );
        """)
        
        # Create indexes for efficient querying
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_workflow_versions_workflow_id 
            ON public.deployed_workflow_versions(workflow_id);
        """)
        
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_workflow_versions_active 
            ON public.deployed_workflow_versions(workflow_id, is_active) 
            WHERE is_active = true;
        """)
        
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_workflow_versions_created_at 
            ON public.deployed_workflow_versions(created_at);
        """)
        
        # Add RLS policies
        cur.execute("""
            ALTER TABLE public.deployed_workflow_versions ENABLE ROW LEVEL SECURITY;
        """)
        
        # Create RLS policies (drop first if they exist)
        cur.execute("""
            DROP POLICY IF EXISTS "Users can read workflow versions" 
            ON public.deployed_workflow_versions;
        """)
        
        cur.execute("""
            CREATE POLICY "Users can read workflow versions" 
            ON public.deployed_workflow_versions
            FOR SELECT USING (true);
        """)
        
        cur.execute("""
            DROP POLICY IF EXISTS "Authenticated users can create versions" 
            ON public.deployed_workflow_versions;
        """)
        
        cur.execute("""
            CREATE POLICY "Authenticated users can create versions" 
            ON public.deployed_workflow_versions
            FOR INSERT WITH CHECK (true);
        """)
        
        # Add comments
        cur.execute("""
            COMMENT ON TABLE public.deployed_workflow_versions IS 
            'Stores all versions of workflow automation sequences with full history';
        """)
        
        cur.execute("""
            COMMENT ON COLUMN public.deployed_workflow_versions.automation_sequence IS 
            'Complete workflow definition for this specific version';
        """)
        
        cur.execute("""
            COMMENT ON COLUMN public.deployed_workflow_versions.is_active IS 
            'Only one version per workflow can be active at a time';
        """)
        
        print("✅ Successfully created deployed_workflow_versions table")

def add_version_tracking_columns(conn):
    """Add version tracking columns to deployed_workflows table."""
    print("📝 Adding version tracking columns to deployed_workflows...")
    
    current_version_id_exists, total_versions_exists = check_version_tracking_columns_exist(conn)
    
    with conn.cursor() as cur:
        if not current_version_id_exists:
            print("  Adding current_version_id column...")
            cur.execute("""
                ALTER TABLE public.deployed_workflows 
                ADD COLUMN current_version_id bigint 
                REFERENCES public.deployed_workflow_versions(id) ON DELETE SET NULL;
            """)
        
        if not total_versions_exists:
            print("  Adding total_versions column...")
            cur.execute("""
                ALTER TABLE public.deployed_workflows 
                ADD COLUMN total_versions integer DEFAULT 1;
            """)
        
        # Create indexes
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_deployed_workflows_current_version 
            ON public.deployed_workflows(current_version_id);
        """)
        
        # Add comments
        cur.execute("""
            COMMENT ON COLUMN public.deployed_workflows.current_version_id IS 
            'Reference to the currently active version of this workflow';
        """)
        
        cur.execute("""
            COMMENT ON COLUMN public.deployed_workflows.total_versions IS 
            'Total number of versions created for this workflow';
        """)
        
        print("✅ Successfully added version tracking columns")

def migrate_existing_data(conn):
    """Migrate existing automation_sequence data to versions table."""
    print("📦 Migrating existing automation sequences to versions table...")
    
    with conn.cursor() as cur:
        # Check if we have any workflows to migrate
        cur.execute("SELECT COUNT(*) FROM deployed_workflows")
        result = cur.fetchone()
        workflow_count = result[0] if result else 0
        
        if workflow_count == 0:
            print("  No workflows to migrate")
            return
        
        print(f"  Found {workflow_count} workflows to migrate...")
        
        # Migrate existing data to versions table
        cur.execute("""
            INSERT INTO public.deployed_workflow_versions 
            (workflow_id, version_number, automation_sequence, is_active, created_by, change_notes)
            SELECT 
                id, 
                COALESCE(version, '1.0.0'), 
                automation_sequence, 
                true, 
                COALESCE(created_by::text, 'system'),
                'Initial version migrated from deployed_workflows table'
            FROM public.deployed_workflows
            WHERE id NOT IN (
                SELECT DISTINCT workflow_id 
                FROM public.deployed_workflow_versions
            );
        """)
        
        migrated_count = cur.rowcount
        print(f"  Migrated {migrated_count} workflow versions")
        
        # Update current_version_id references
        cur.execute("""
            UPDATE public.deployed_workflows 
            SET current_version_id = v.id,
                total_versions = 1
            FROM public.deployed_workflow_versions v 
            WHERE deployed_workflows.id = v.workflow_id 
            AND v.is_active = true
            AND deployed_workflows.current_version_id IS NULL;
        """)
        
        updated_count = cur.rowcount
        print(f"  Updated {updated_count} workflow references")
        
        print("✅ Successfully migrated existing data")

def add_version_tracking_to_executions(conn):
    """Add version tracking to workflow_executions table."""
    print("📝 Adding version tracking to workflow_executions...")
    
    with conn.cursor() as cur:
        # Check if columns already exist
        cur.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'workflow_executions' 
                AND column_name = 'workflow_version_id'
            )
        """)
        result1 = cur.fetchone()
        version_id_exists = result1[0] if result1 else False
        
        cur.execute("""
            SELECT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'workflow_executions' 
                AND column_name = 'workflow_version_number'
            )
        """)
        result2 = cur.fetchone()
        version_number_exists = result2[0] if result2 else False
        
        if not version_id_exists:
            print("  Adding workflow_version_id column...")
            cur.execute("""
                ALTER TABLE public.workflow_executions 
                ADD COLUMN workflow_version_id bigint 
                REFERENCES public.deployed_workflow_versions(id) ON DELETE SET NULL;
            """)
        
        if not version_number_exists:
            print("  Adding workflow_version_number column...")
            cur.execute("""
                ALTER TABLE public.workflow_executions 
                ADD COLUMN workflow_version_number text;
            """)
        
        # Create index for version queries
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_executions_version 
            ON public.workflow_executions(workflow_version_id);
        """)
        
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_executions_version_number 
            ON public.workflow_executions(workflow_version_number);
        """)
        
        # Add comments
        cur.execute("""
            COMMENT ON COLUMN public.workflow_executions.workflow_version_id IS 
            'Reference to the specific version that was executed';
        """)
        
        cur.execute("""
            COMMENT ON COLUMN public.workflow_executions.workflow_version_number IS 
            'Denormalized version number for fast queries (e.g., 1.0.5)';
        """)
        
        print("✅ Successfully added version tracking to executions")

def update_workflow_version_trigger(conn):
    """Update the workflow versioning trigger."""
    print("🔧 Updating workflow versioning trigger...")
    
    with conn.cursor() as cur:
        # Drop old trigger if it exists
        cur.execute("""
            DROP TRIGGER IF EXISTS trigger_autoincrement_workflow_version 
            ON public.deployed_workflows;
        """)
        
        # Create new version creation function
        cur.execute("""
            CREATE OR REPLACE FUNCTION create_new_workflow_version()
            RETURNS TRIGGER AS $$
            DECLARE
                new_version_number text;
                new_version_id bigint;
            BEGIN
                -- Only create new version if automation_sequence actually changed
                IF NEW.automation_sequence IS DISTINCT FROM OLD.automation_sequence THEN
                    -- Generate next version number
                    new_version_number := increment_version(OLD.version);
                    
                    -- Create new version record
                    INSERT INTO public.deployed_workflow_versions 
                    (workflow_id, version_number, automation_sequence, is_active, created_by, change_notes)
                    VALUES (NEW.id, new_version_number, NEW.automation_sequence, false, COALESCE(NEW.created_by::text, 'system'), 'Updated via automation_sequence change')
                    RETURNING id INTO new_version_id;
                    
                    -- Deactivate old version
                    UPDATE public.deployed_workflow_versions 
                    SET is_active = false 
                    WHERE workflow_id = NEW.id AND id != new_version_id;
                    
                    -- Activate new version
                    UPDATE public.deployed_workflow_versions 
                    SET is_active = true 
                    WHERE id = new_version_id;
                    
                    -- Update workflow metadata
                    NEW.version = new_version_number;
                    NEW.total_versions = OLD.total_versions + 1;
                    NEW.current_version_id = new_version_id;
                END IF;
                
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)
        
        # Create new trigger
        cur.execute("""
            CREATE TRIGGER trigger_create_workflow_version
            BEFORE UPDATE ON public.deployed_workflows
            FOR EACH ROW EXECUTE FUNCTION create_new_workflow_version();
        """)
        
        cur.execute("""
            COMMENT ON FUNCTION create_new_workflow_version() IS 
            'Creates new version when automation_sequence changes, maintains version history';
        """)
        
        print("✅ Successfully updated workflow versioning trigger")

def create_compatibility_views(conn):
    """Create views for backward compatibility."""
    print("📝 Creating compatibility views...")
    
    with conn.cursor() as cur:
        # Create view that includes automation_sequence from current version
        cur.execute("""
            CREATE OR REPLACE VIEW public.deployed_workflows_with_sequence AS
            SELECT 
                w.id, w.name, w.description, w.status, w.category,
                w.successful_runs, w.failed_runs, w.cancelled_runs, w.total_executions,
                w.estimated_duration_seconds, w.workflow_type, w.parent_workflow_id, w.display_order,
                w.created_by, w.created_at, w.updated_at,
                w.current_version_id, w.total_versions,
                v.automation_sequence,
                v.version_number as version,
                v.change_notes as current_version_notes
            FROM public.deployed_workflows w
            LEFT JOIN public.deployed_workflow_versions v ON w.current_version_id = v.id;
        """)
        
        # Create view for execution history with version info
        cur.execute("""
            CREATE OR REPLACE VIEW public.workflow_execution_history AS
            SELECT 
                e.*,
                w.name as workflow_name,
                v.version_number,
                v.change_notes as version_notes
            FROM public.workflow_executions e
            JOIN public.deployed_workflows w ON e.workflow_id = w.id
            LEFT JOIN public.deployed_workflow_versions v ON e.workflow_version_id = v.id;
        """)
        
        # Add comments
        cur.execute("""
            COMMENT ON VIEW public.deployed_workflows_with_sequence IS 
            'Backward compatibility view that includes automation_sequence from current active version';
        """)
        
        cur.execute("""
            COMMENT ON VIEW public.workflow_execution_history IS 
            'Complete execution history with version information for traceability';
        """)
        
        print("✅ Successfully created compatibility views")

def create_version_management_functions(conn):
    """Create functions for version management operations."""
    print("🔧 Creating version management functions...")
    
    with conn.cursor() as cur:
        # Function to activate a specific version
        cur.execute("""
            CREATE OR REPLACE FUNCTION activate_workflow_version(
                p_workflow_id bigint,
                p_version_number text
            ) RETURNS boolean AS $$
            DECLARE
                target_version_id bigint;
            BEGIN
                -- Find the target version
                SELECT id INTO target_version_id
                FROM public.deployed_workflow_versions
                WHERE workflow_id = p_workflow_id AND version_number = p_version_number;
                
                IF target_version_id IS NULL THEN
                    RAISE EXCEPTION 'Version % not found for workflow %', p_version_number, p_workflow_id;
                END IF;
                
                -- Deactivate all versions for this workflow
                UPDATE public.deployed_workflow_versions
                SET is_active = false
                WHERE workflow_id = p_workflow_id;
                
                -- Activate target version
                UPDATE public.deployed_workflow_versions
                SET is_active = true
                WHERE id = target_version_id;
                
                -- Update main workflow record
                UPDATE public.deployed_workflows
                SET current_version_id = target_version_id,
                    version = p_version_number,
                    updated_at = now()
                WHERE id = p_workflow_id;
                
                RETURN true;
            END;
            $$ LANGUAGE plpgsql SECURITY DEFINER;
        """)
        
        # Function to get version history
        cur.execute("""
            CREATE OR REPLACE FUNCTION get_workflow_version_history(p_workflow_id bigint)
            RETURNS TABLE(
                version_id bigint,
                version_number text,
                is_active boolean,
                created_at timestamptz,
                change_notes text,
                execution_count bigint
            ) AS $$
            BEGIN
                RETURN QUERY
                SELECT 
                    v.id,
                    v.version_number,
                    v.is_active,
                    v.created_at,
                    v.change_notes,
                    COUNT(e.id) as execution_count
                FROM public.deployed_workflow_versions v
                LEFT JOIN public.workflow_executions e ON v.id = e.workflow_version_id
                WHERE v.workflow_id = p_workflow_id
                GROUP BY v.id, v.version_number, v.is_active, v.created_at, v.change_notes
                ORDER BY v.created_at DESC;
            END;
            $$ LANGUAGE plpgsql SECURITY DEFINER;
        """)
        
        # Add comments
        cur.execute("""
            COMMENT ON FUNCTION activate_workflow_version(bigint, text) IS 
            'Activates a specific version of a workflow (rollback/rollforward)';
        """)
        
        cur.execute("""
            COMMENT ON FUNCTION get_workflow_version_history(bigint) IS 
            'Returns complete version history for a workflow with execution counts';
        """)
        
        print("✅ Successfully created version management functions")

def verify_implementation(conn):
    """Verify that the versioning implementation is working correctly."""
    print("🔍 Verifying implementation...")
    
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        # Check table exists
        cur.execute("""
            SELECT table_name FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = 'deployed_workflow_versions'
        """)
        table_result = cur.fetchone()
        if not table_result:
            print("❌ deployed_workflow_versions table not found")
            return False
        
        # Check data migration
        cur.execute("SELECT COUNT(*) FROM public.deployed_workflow_versions")
        version_result = cur.fetchone()
        version_count = version_result[0] if version_result else 0
        
        cur.execute("SELECT COUNT(*) FROM public.deployed_workflows WHERE current_version_id IS NOT NULL")
        linked_result = cur.fetchone()
        linked_count = linked_result[0] if linked_result else 0
        
        cur.execute("SELECT COUNT(*) FROM public.deployed_workflows")
        total_result = cur.fetchone()
        total_workflows = total_result[0] if total_result else 0
        
        print(f"  📊 Statistics:")
        print(f"    - Total workflows: {total_workflows}")
        print(f"    - Migrated versions: {version_count}")
        print(f"    - Linked workflows: {linked_count}")
        
        # Test the compatibility view
        cur.execute("""
            SELECT COUNT(*) FROM public.deployed_workflows_with_sequence 
            WHERE automation_sequence IS NOT NULL
        """)
        view_result = cur.fetchone()
        view_count = view_result[0] if view_result else 0
        print(f"    - Workflows accessible via compatibility view: {view_count}")
        
        # Test version management function
        if total_workflows > 0:
            cur.execute("SELECT id FROM public.deployed_workflows LIMIT 1")
            test_result = cur.fetchone()
            test_workflow_id = test_result[0] if test_result else None
            
            cur.execute("SELECT * FROM get_workflow_version_history(%s)", (test_workflow_id,))
            history = cur.fetchall()
            print(f"    - Version history test: {len(history)} versions found for workflow {test_workflow_id}")
        
        if version_count == total_workflows and linked_count == total_workflows:
            print("✅ Implementation verification successful!")
            return True
        else:
            print("❌ Implementation verification failed - data mismatch")
            return False

def main():
    """Main function to implement workflow versioning."""
    print("🚀 Starting workflow versioning implementation...")
    print(f"Started at: {datetime.now()}")
    
    conn = get_db_connection()
    conn.autocommit = False  # Use transactions for safety
    
    try:
        # Check if already implemented
        if check_versions_table_exists(conn):
            print("⚠️  Versioning table already exists. Checking implementation...")
            
            # Verify current implementation
            if verify_implementation(conn):
                print("✅ Versioning system already fully implemented!")
                return True
            else:
                print("🔧 Completing partial implementation...")
        
        print("\n" + "="*60)
        print("PHASE 1: Creating version storage infrastructure")
        print("="*60)
        
        # Step 1: Create versions table
        create_workflow_versions_table(conn)
        
        # Step 2: Add version tracking columns  
        add_version_tracking_columns(conn)
        
        # Step 3: Migrate existing data
        migrate_existing_data(conn)
        
        print("\n" + "="*60)
        print("PHASE 2: Adding execution traceability")
        print("="*60)
        
        # Step 4: Add version tracking to executions
        add_version_tracking_to_executions(conn)
        
        print("\n" + "="*60)
        print("PHASE 3: Updating triggers and functions")
        print("="*60)
        
        # Step 5: Update versioning triggers
        update_workflow_version_trigger(conn)
        
        # Step 6: Create management functions
        create_version_management_functions(conn)
        
        print("\n" + "="*60)
        print("PHASE 4: Creating compatibility layer")
        print("="*60)
        
        # Step 7: Create compatibility views
        create_compatibility_views(conn)
        
        # Commit all changes
        conn.commit()
        
        print("\n" + "="*60)
        print("VERIFICATION")
        print("="*60)
        
        # Step 8: Verify implementation
        if verify_implementation(conn):
            print("\n🎉 Workflow versioning implementation completed successfully!")
            print("\n📋 What was implemented:")
            print("   ✅ Version history storage (deployed_workflow_versions table)")
            print("   ✅ Version tracking in main workflow table") 
            print("   ✅ Execution version traceability")
            print("   ✅ Automatic version creation on changes")
            print("   ✅ Version management functions (activate_workflow_version)")
            print("   ✅ Backward compatibility views")
            print("   ✅ Data migration from existing workflows")
            
            print("\n🔧 Available functions:")
            print("   - activate_workflow_version(workflow_id, version_number)")
            print("   - get_workflow_version_history(workflow_id)")
            
            print("\n📊 Available views:")
            print("   - deployed_workflows_with_sequence (backward compatibility)")
            print("   - workflow_execution_history (with version info)")
            
            print(f"\nCompleted at: {datetime.now()}")
            return True
        else:
            print("❌ Implementation verification failed!")
            conn.rollback()
            return False
            
    except Exception as e:
        print(f"❌ Error during implementation: {e}")
        conn.rollback()
        raise
    finally:
        conn.close()

if __name__ == "__main__":
    try:
        success = main()
        if success:
            print("\n✅ Workflow versioning system is ready to use!")
        else:
            print("\n❌ Implementation failed!")
            exit(1)
    except Exception as e:
        print(f"\n💥 Fatal error: {e}")
        exit(1) 