create table public.low_level_workflows (
  id bigint generated by default as identity not null,
  user_id uuid null,
  title text null,
  inputs text[] null,
  outputs text[] null,
  steps text[] null,
  business_logic text[] null,
  created_at timestamp with time zone null default now(),
  constraint low_level_workflows_pkey primary key (id)
) tablespace pg_default; 