-- Drop the table if it exists to ensure a clean slate
DROP TABLE IF EXISTS public.low_level_workflow_labeling;

-- Recreate the table following the pattern of low_level_workflow_analyses
create table public.low_level_workflow_labeling (
  id bigint generated by default as identity not null,
  user_id uuid null, -- No foreign key constraint to public.users
  low_level_workflow_analysis_id bigint null,
  suggested_labels text[] null,
  selected_labels text[] null,
  created_at timestamp with time zone null default now(),
  constraint low_level_workflow_labeling_pkey primary key (id),
  constraint low_level_workflow_labeling_analysis_id_fkey foreign key (low_level_workflow_analysis_id) references public.low_level_workflow_analyses (id) on delete cascade,
  constraint unique_analysis_labeling unique (low_level_workflow_analysis_id)
) tablespace pg_default; 