CREATE TABLE public.low_level_workflow_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  session_id TEXT,
  workflow TEXT,
  step TEXT,
  description TEXT,
  facts TEXT,
  logic TEXT,
  tech TEXT,
  apps TEXT,
  context TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  client_timestamp TIMESTAMPTZ
);

ALTER TABLE public.low_level_workflow_analyses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated user to insert their own analyses"
ON public.low_level_workflow_analyses
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow authenticated user to view their own analyses"
ON public.low_level_workflow_analyses
FOR SELECT
TO authenticated
USING (auth.uid() = user_id); 