-- Migration: Add transcript integration and user instructions support
-- Created: 2025-01-30
-- Description: Adds transcript storage, user instructions, and enhances workflow synthesis with conversation context

-- Create agent_live_transcriptions table for storing conversation transcripts
CREATE TABLE agent_live_transcriptions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id text NOT NULL,
    user_id uuid,
    lead_id text,
    item_id text NOT NULL,
    type text NOT NULL,
    role text NOT NULL,
    content text[] NOT NULL,
    interrupted boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Index for efficient transcript queries
CREATE INDEX idx_transcriptions_session_id ON agent_live_transcriptions(session_id);
CREATE INDEX idx_transcriptions_user_id ON agent_live_transcriptions(user_id);
CREATE INDEX idx_transcriptions_created_at ON agent_live_transcriptions(created_at);
CREATE INDEX idx_transcriptions_user_session ON agent_live_transcriptions(user_id, session_id);

-- Enhance synthesis_sessions table with user instructions
ALTER TABLE synthesis_sessions 
ADD COLUMN user_instructions text,
ADD COLUMN related_transcript_sessions text[],
ADD COLUMN transcript_summary text;

-- Enhance low_level_workflow_analyses with transcript relationships
ALTER TABLE low_level_workflow_analyses 
ADD COLUMN related_transcript_sessions text[],
ADD COLUMN conversation_context text;

-- =============================================================================
-- Create a view for enriched workflow analyses with transcript context
-- =============================================================================
CREATE OR REPLACE VIEW workflow_analyses_with_transcripts AS
SELECT 
    wa.*,
    COALESCE(
        array_agg(DISTINCT t.session_id) FILTER (WHERE t.session_id IS NOT NULL),
        '{}'::text[]
    ) as available_transcript_sessions,
    COALESCE(
        string_agg(DISTINCT t.content::text, ' | ') FILTER (WHERE t.content IS NOT NULL),
        ''
    ) as transcript_excerpt
FROM low_level_workflow_analyses wa
LEFT JOIN agent_live_transcriptions t ON 
    t.user_id = wa.user_id 
    AND t.created_at BETWEEN (wa.client_timestamp - interval '1 hour') 
    AND (wa.client_timestamp + interval '1 hour')
GROUP BY wa.id, wa.user_id, wa.session_id, wa.llm_structured_output, wa.client_timestamp, wa.window_title, wa.created_at, wa.updated_at, wa.related_transcript_sessions, wa.conversation_context;

-- =============================================================================
-- Function to get transcripts for a time range and user
-- =============================================================================
CREATE OR REPLACE FUNCTION get_transcripts_for_time_range(
    p_user_id uuid,
    p_start_time timestamp with time zone,
    p_end_time timestamp with time zone
) RETURNS TABLE (
    session_id text,
    role text,
    content text[],
    created_at timestamp with time zone,
    type text
) LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
    SELECT 
        t.session_id,
        t.role,
        t.content,
        t.created_at,
        t.type
    FROM agent_live_transcriptions t
    WHERE t.user_id = p_user_id
      AND t.created_at BETWEEN p_start_time AND p_end_time
    ORDER BY t.created_at ASC;
END;
$$;

-- =============================================================================
-- Function to format transcripts for LLM prompts
-- =============================================================================
CREATE OR REPLACE FUNCTION format_transcripts_for_prompt(
    p_user_id uuid,
    p_start_time timestamp with time zone,
    p_end_time timestamp with time zone,
    p_max_length integer DEFAULT 2000
) RETURNS text LANGUAGE plpgsql AS $$
DECLARE
    formatted_transcript text := '';
    current_length integer := 0;
    transcript_record record;
BEGIN
    FOR transcript_record IN
        SELECT 
            session_id,
            role,
            content,
            created_at,
            type
        FROM agent_live_transcriptions
        WHERE user_id = p_user_id
          AND created_at BETWEEN p_start_time AND p_end_time
        ORDER BY created_at ASC
    LOOP
        -- Format each transcript entry
        DECLARE
            entry_text text := format('[%s] %s: %s', 
                transcript_record.created_at::time,
                transcript_record.role,
                array_to_string(transcript_record.content, ' ')
            );
        BEGIN
            -- Check if adding this entry would exceed max length
            IF current_length + length(entry_text) > p_max_length THEN
                formatted_transcript := formatted_transcript || '... (truncated)';
                EXIT;
            END IF;
            
            formatted_transcript := formatted_transcript || entry_text || E'\n';
            current_length := current_length + length(entry_text) + 1;
        END;
    END LOOP;
    
    RETURN COALESCE(formatted_transcript, 'No transcript data available for this time range.');
END;
$$; 