-- Add GitHub reference columns to deployed_workflows table
-- This allows workflows to be stored in GitHub while metadata remains in Supabase

-- Add columns for GitHub references
ALTER TABLE public.deployed_workflows
ADD COLUMN IF NOT EXISTS github_path text,
ADD COLUMN IF NOT EXISTS github_ref text DEFAULT 'main',
ADD COLUMN IF NOT EXISTS github_sha text,
ADD COLUMN IF NOT EXISTS github_sync_status text DEFAULT 'pending'
    CHECK (github_sync_status IN ('pending', 'synced', 'failed', 'out_of_sync'));

-- Add index for GitHub path lookups
CREATE INDEX IF NOT EXISTS idx_deployed_workflows_github_path
    ON public.deployed_workflows(github_path)
    WHERE github_path IS NOT NULL;

-- Add column to track sync timestamps
ALTER TABLE public.deployed_workflows
ADD COLUMN IF NOT EXISTS github_last_synced_at timestamp with time zone;

-- Create a tracking table for GitHub sync operations
CREATE TABLE IF NOT EXISTS public.github_workflow_sync_log (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_id bigint REFERENCES public.deployed_workflows(id) ON DELETE CASCADE,
    operation text NOT NULL CHECK (operation IN ('push', 'pull', 'sync')),
    github_path text,
    github_sha text,
    status text NOT NULL CHECK (status IN ('success', 'failed', 'partial')),
    error_message text,
    created_at timestamp with time zone DEFAULT now(),
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Index for sync log queries
CREATE INDEX IF NOT EXISTS idx_github_sync_log_workflow
    ON public.github_workflow_sync_log(workflow_id);
CREATE INDEX IF NOT EXISTS idx_github_sync_log_created
    ON public.github_workflow_sync_log(created_at DESC);

-- Add comment for documentation
COMMENT ON COLUMN public.deployed_workflows.github_path IS 'Path to workflow in GitHub repository (e.g., production/bestplanpro/workflow.yaml)';
COMMENT ON COLUMN public.deployed_workflows.github_ref IS 'Git reference (branch/tag/commit) to use for this workflow';
COMMENT ON COLUMN public.deployed_workflows.github_sha IS 'Specific commit SHA for version pinning';
COMMENT ON COLUMN public.deployed_workflows.github_sync_status IS 'Status of synchronization with GitHub repository';
COMMENT ON TABLE public.github_workflow_sync_log IS 'Audit log for GitHub workflow synchronization operations';