-- Create table to track processed screenshot_diff events
CREATE TABLE IF NOT EXISTS public.low_level_processed_screenshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL UNIQUE,
    user_id TEXT,
    session_id TEXT,
    before_path TEXT,
    after_path TEXT,
    before_size INTEGER,
    after_size INTEGER,
    processing_failed BOOLEAN DEFAULT FALSE,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_processed_screenshots_event_id ON public.low_level_processed_screenshots(event_id);
CREATE INDEX IF NOT EXISTS idx_processed_screenshots_user_id ON public.low_level_processed_screenshots(user_id);
CREATE INDEX IF NOT EXISTS idx_processed_screenshots_session_id ON public.low_level_processed_screenshots(session_id);

COMMENT ON TABLE public.low_level_processed_screenshots IS 'Tracks which screenshot_diff events have been processed and their storage paths.';
