CREATE TABLE IF NOT EXISTS public.screenshot_processing_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL UNIQUE,
    processor_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE public.screenshot_processing_locks IS 'Manages distributed locks for the screenshot processor to prevent race conditions.'; 