-- Create raw_timeline_event_annotations table for mapping raw events to workflow analyses
-- This enables granular tracking of how individual user interactions map to workflow steps

CREATE TABLE IF NOT EXISTS public.raw_timeline_event_annotations (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- Core relationships
    raw_event_id bigint REFERENCES public.low_level_events(id) ON DELETE CASCADE,
    analysis_id bigint REFERENCES public.low_level_workflow_analyses(id) ON DELETE CASCADE,
    
    -- Mapping classification  
    is_workflow_related boolean NOT NULL,
    
    -- Event context details (from LLM analysis)
    user_action text,
    ui_element_interacted text,
    content_change text,
    timestamp_context text,
    
    -- Unrelated event details
    unrelated_reason text,
    
    -- Analysis metadata
    confidence_score decimal(3,2) CHECK (confidence_score >= 0 AND confidence_score <= 1),
    model_used text DEFAULT 'gemini-2.5-pro', -- gemini-2.5-flash-preview-05-20
    
    -- Tracking
    user_id uuid NOT NULL,
    session_id text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- Add comments to explain the purpose of each column
COMMENT ON TABLE public.raw_timeline_event_annotations IS 'Maps individual raw events to workflow analyses for granular workflow tracking';
COMMENT ON COLUMN public.raw_timeline_event_annotations.raw_event_id IS 'Foreign key to low_level_events.id - the raw event being mapped';
COMMENT ON COLUMN public.raw_timeline_event_annotations.analysis_id IS 'Foreign key to low_level_workflow_analyses.id - the workflow analysis this event contributes to';
COMMENT ON COLUMN public.raw_timeline_event_annotations.is_workflow_related IS 'Whether this raw event contributes to a workflow step or is unrelated';
COMMENT ON COLUMN public.raw_timeline_event_annotations.user_action IS 'Description of the user action from this raw event';
COMMENT ON COLUMN public.raw_timeline_event_annotations.ui_element_interacted IS 'UI element the user interacted with';
COMMENT ON COLUMN public.raw_timeline_event_annotations.content_change IS 'How the content changed as a result of this event';
COMMENT ON COLUMN public.raw_timeline_event_annotations.timestamp_context IS 'Temporal context of when this event occurred in the workflow';
COMMENT ON COLUMN public.raw_timeline_event_annotations.unrelated_reason IS 'Explanation of why this event is not related to any workflow';

-- Add foreign key constraints
ALTER TABLE public.raw_timeline_event_annotations 
ADD CONSTRAINT raw_timeline_annotations_user_id_fkey 
FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Add indexes for performance
CREATE INDEX idx_raw_timeline_annotations_raw_event_id ON public.raw_timeline_event_annotations(raw_event_id);
CREATE INDEX idx_raw_timeline_annotations_analysis_id ON public.raw_timeline_event_annotations(analysis_id);
CREATE INDEX idx_raw_timeline_annotations_user_id ON public.raw_timeline_event_annotations(user_id);
CREATE INDEX idx_raw_timeline_annotations_is_workflow_related ON public.raw_timeline_event_annotations(is_workflow_related);
CREATE INDEX idx_raw_timeline_annotations_user_session ON public.raw_timeline_event_annotations(user_id, session_id);

-- Ensure no duplicate mappings for the same raw event
CREATE UNIQUE INDEX idx_raw_timeline_annotations_unique_event 
ON public.raw_timeline_event_annotations(raw_event_id, analysis_id) 
WHERE analysis_id IS NOT NULL; 