-- Migration: Create deployed_workflows table for remote workflow execution
-- Created: 2025-06-30
-- Description: Stores deployable workflow definitions that can be executed remotely via Modal

CREATE TABLE IF NOT EXISTS public.deployed_workflows (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- Basic workflow information
    name text NOT NULL,
    description text,
    version text DEFAULT '1.0.0',
    status text DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'draft', 'deprecated')),
    
    -- Workflow definition (YAML structure as JSON)
    automation_sequence jsonb NOT NULL,
    validation_checks jsonb,
    error_handling jsonb,
    
    -- Input/Output definitions
    input_parameters jsonb DEFAULT '{}', -- Parameter schema and defaults
    expected_outputs jsonb DEFAULT '{}', -- Expected output schema
    sample_inputs jsonb DEFAULT '{}', -- Example inputs for testing
    
    -- Execution metadata
    estimated_duration_seconds integer,
    
    -- Classification and organization
    category text DEFAULT 'general',
    tags text[] DEFAULT '{}',
    difficulty_level text DEFAULT 'medium' CHECK (difficulty_level IN ('easy', 'medium', 'hard', 'expert')),
    
    -- Execution statistics
    successful_runs integer DEFAULT 0,
    failed_runs integer DEFAULT 0,
    total_executions integer DEFAULT 0,
    last_successful_execution timestamp with time zone,
    last_failed_execution timestamp with time zone,
    
    -- Metadata
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    
    -- Deployment info
    modal_function_name text, -- Reference to Modal function
    deployment_status text DEFAULT 'pending' CHECK (deployment_status IN ('pending', 'deployed', 'failed', 'updating')),
    last_deployed_at timestamp with time zone
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_deployed_workflows_status ON public.deployed_workflows(status);
CREATE INDEX IF NOT EXISTS idx_deployed_workflows_category ON public.deployed_workflows(category);
CREATE INDEX IF NOT EXISTS idx_deployed_workflows_tags ON public.deployed_workflows USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_deployed_workflows_created_by ON public.deployed_workflows(created_by);
CREATE INDEX IF NOT EXISTS idx_deployed_workflows_deployment_status ON public.deployed_workflows(deployment_status);

-- Add RLS policies
ALTER TABLE public.deployed_workflows ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read active workflows
CREATE POLICY "Users can read active workflows" ON public.deployed_workflows
    FOR SELECT USING (status = 'active');

-- Policy: Authenticated users can create workflows
CREATE POLICY "Authenticated users can create workflows" ON public.deployed_workflows
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Policy: Users can update their own workflows
CREATE POLICY "Users can update own workflows" ON public.deployed_workflows
    FOR UPDATE USING (created_by = auth.uid());

-- Policy: Users can delete their own workflows
CREATE POLICY "Users can delete own workflows" ON public.deployed_workflows
    FOR DELETE USING (created_by = auth.uid());

-- Add trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_deployed_workflows_updated_at 
    BEFORE UPDATE ON public.deployed_workflows 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE public.deployed_workflows IS 'Stores deployable workflow definitions for remote execution via Modal';
COMMENT ON COLUMN public.deployed_workflows.automation_sequence IS 'Complete workflow definition including steps, actions, and selectors';
COMMENT ON COLUMN public.deployed_workflows.input_parameters IS 'Schema defining required and optional input parameters';
COMMENT ON COLUMN public.deployed_workflows.expected_outputs IS 'Schema defining expected workflow outputs and results';
COMMENT ON COLUMN public.deployed_workflows.modal_function_name IS 'Name of the deployed Modal function for this workflow';
COMMENT ON COLUMN public.deployed_workflows.successful_runs IS 'Count of successful workflow executions';
COMMENT ON COLUMN public.deployed_workflows.failed_runs IS 'Count of failed workflow executions';
COMMENT ON COLUMN public.deployed_workflows.automation_sequence IS 'Cross-application automation steps spanning browsers, desktop apps, and system interactions';
