
-- =============================================================================
-- Timeline Workflow Mapping Enhancement
-- Adds workflow types, instances, and timeline event mappings
-- =============================================================================

-- 1. Workflow Types/Branches Table
CREATE TABLE IF NOT EXISTS public.workflow_types (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_template_id bigint REFERENCES public.low_level_workflows(id) ON DELETE CASCADE,
    type_name text NOT NULL,                    -- "Premium Path", "Express Order"
    type_description text,                      -- Human readable description
    conditions jsonb DEFAULT '{}',              -- Conditions that trigger this type
    user_id uuid NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT unique_workflow_type UNIQUE(workflow_template_id, type_name)
);

-- 2. Workflow Instances Table  
CREATE TABLE IF NOT EXISTS public.workflow_instances (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_type_id bigint REFERENCES public.workflow_types(id) ON DELETE CASCADE,
    instance_name text NOT NULL,                -- "Customer: John Doe", "Order: #12345"
    instance_data jsonb DEFAULT '{}',           -- Structured data about this instance
    status text DEFAULT 'active',              -- active, completed, failed, paused
    started_at timestamptz,
    completed_at timestamptz,
    user_id uuid NOT NULL,
    session_id text,                           -- Link to synthesis session
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT workflow_instance_status_check CHECK (status IN ('active', 'completed', 'failed', 'paused'))
);

-- 3. Timeline Event to Workflow Mappings (Main Table)
CREATE TABLE IF NOT EXISTS public.timeline_event_workflow_mappings (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- Core relationships
    timeline_event_id bigint REFERENCES public.low_level_events(id) ON DELETE CASCADE,
    workflow_template_id bigint REFERENCES public.low_level_workflows(id) ON DELETE CASCADE,
    workflow_type_id bigint REFERENCES public.workflow_types(id) ON DELETE CASCADE,
    workflow_instance_id bigint REFERENCES public.workflow_instances(id) ON DELETE CASCADE,
    
    -- Step hierarchy
    workflow_step text NOT NULL,               -- Step name within workflow
    workflow_substep text,                     -- Optional substep breakdown
    step_sequence integer,                     -- Order within workflow (optional)
    
    -- Event context (flexible arrays)
    event_inputs text[] DEFAULT '{}',          -- What led to this event
    event_outputs text[] DEFAULT '{}',         -- What this event produced
    business_logics text[] DEFAULT '{}',       -- Rules governing this event
    
    -- Metadata
    confidence_score decimal(3,2) CHECK (confidence_score >= 0 AND confidence_score <= 1),
    analysis_timestamp timestamptz DEFAULT now(),
    model_used text DEFAULT 'gpt-4',
    
    -- Tracking
    user_id uuid NOT NULL,
    session_id text,
    created_at timestamptz DEFAULT now(),
    
    -- Ensure no duplicate mappings
    CONSTRAINT unique_timeline_workflow_mapping 
        UNIQUE(timeline_event_id, workflow_instance_id, workflow_step, workflow_substep)
);

-- 4. Unrelated Timeline Events Table
CREATE TABLE IF NOT EXISTS public.timeline_event_unrelated (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timeline_event_id bigint REFERENCES public.low_level_events(id) ON DELETE CASCADE,
    reason text NOT NULL,                      -- Why this event is unrelated
    confidence_score decimal(3,2) CHECK (confidence_score >= 0 AND confidence_score <= 1),
    analysis_timestamp timestamptz DEFAULT now(),
    model_used text DEFAULT 'gpt-4',
    user_id uuid NOT NULL,
    session_id text,
    created_at timestamptz DEFAULT now(),
    
    CONSTRAINT unique_unrelated_event UNIQUE(timeline_event_id)
);

-- =============================================================================
-- Indexes for Performance
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_workflow_types_template ON workflow_types(workflow_template_id);
CREATE INDEX IF NOT EXISTS idx_workflow_types_user ON workflow_types(user_id);

CREATE INDEX IF NOT EXISTS idx_workflow_instances_type ON workflow_instances(workflow_type_id);
CREATE INDEX IF NOT EXISTS idx_workflow_instances_user ON workflow_instances(user_id);
CREATE INDEX IF NOT EXISTS idx_workflow_instances_session ON workflow_instances(session_id);

CREATE INDEX IF NOT EXISTS idx_timeline_mappings_event ON timeline_event_workflow_mappings(timeline_event_id);
CREATE INDEX IF NOT EXISTS idx_timeline_mappings_template ON timeline_event_workflow_mappings(workflow_template_id);
CREATE INDEX IF NOT EXISTS idx_timeline_mappings_instance ON timeline_event_workflow_mappings(workflow_instance_id);
CREATE INDEX IF NOT EXISTS idx_timeline_mappings_user_session ON timeline_event_workflow_mappings(user_id, session_id);

CREATE INDEX IF NOT EXISTS idx_timeline_unrelated_event ON timeline_event_unrelated(timeline_event_id);
CREATE INDEX IF NOT EXISTS idx_timeline_unrelated_user ON timeline_event_unrelated(user_id);

-- =============================================================================
-- Row Level Security (RLS) Policies
-- =============================================================================
ALTER TABLE workflow_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeline_event_workflow_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeline_event_unrelated ENABLE ROW LEVEL SECURITY;

-- Policies for workflow_types
CREATE POLICY "Users can manage their own workflow types" ON workflow_types
    FOR ALL USING (auth.uid() = user_id);

-- Policies for workflow_instances  
CREATE POLICY "Users can manage their own workflow instances" ON workflow_instances
    FOR ALL USING (auth.uid() = user_id);

-- Policies for timeline_event_workflow_mappings
CREATE POLICY "Users can manage their own timeline mappings" ON timeline_event_workflow_mappings
    FOR ALL USING (auth.uid() = user_id);

-- Policies for timeline_event_unrelated
CREATE POLICY "Users can manage their own unrelated events" ON timeline_event_unrelated
    FOR ALL USING (auth.uid() = user_id);

-- =============================================================================
-- Grant Permissions
-- =============================================================================
GRANT ALL ON workflow_types TO authenticated;
GRANT ALL ON workflow_instances TO authenticated;  
GRANT ALL ON timeline_event_workflow_mappings TO authenticated;
GRANT ALL ON timeline_event_unrelated TO authenticated;

-- Grant sequence permissions
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- =============================================================================
-- Comments for Documentation
-- =============================================================================
COMMENT ON TABLE workflow_types IS 'Different branches/paths a workflow can take (e.g., Premium vs Standard customer onboarding)';
COMMENT ON TABLE workflow_instances IS 'Specific data entity instances being processed through workflows (e.g., Customer: John Doe)';
COMMENT ON TABLE timeline_event_workflow_mappings IS 'Maps individual timeline events to specific workflow instances with detailed context';
COMMENT ON TABLE timeline_event_unrelated IS 'Timeline events that do not belong to any business workflow';

-- =============================================================================
-- Example Data for Testing (Optional - Remove in production)
-- =============================================================================
-- You can add sample data here for testing purposes
