-- Migration: Create workflow execution tracking table
-- Created: 2025-06-30
-- Description: Tracks individual workflow executions for remote clients

CREATE TABLE IF NOT EXISTS public.workflow_executions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- Workflow reference
    workflow_id bigint NOT NULL REFERENCES public.deployed_workflows(id) ON DELETE CASCADE,
    
    -- Client information
    client_id text NOT NULL, -- API key or client identifier
    client_ip inet,
    user_agent text,
    
    -- Execution details
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'completed', 'failed', 'cancelled', 'timeout')),
    execution_params jsonb NOT NULL DEFAULT '{}', -- Input parameters provided by client
    
    -- Results and logs
    results jsonb, -- Final execution results
    execution_logs text[], -- Step-by-step execution logs
    error_message text, -- Error details if failed
    screenshots text[], -- Base64 encoded screenshots
    
    -- Timing
    queued_at timestamp with time zone DEFAULT now(),
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    execution_duration_seconds integer,
    
    -- Modal integration
    modal_call_id text, -- Modal function call ID for tracking
    modal_logs jsonb, -- Raw Modal execution logs
    
    -- Billing and usage
    compute_cost_cents integer DEFAULT 0, -- Cost in cents
    priority integer DEFAULT 5 CHECK (priority BETWEEN 1 AND 10), -- 1=highest, 10=lowest
    
    -- Metadata
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_workflow_executions_workflow_id ON public.workflow_executions(workflow_id);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_client_id ON public.workflow_executions(client_id);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_status ON public.workflow_executions(status);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_created_at ON public.workflow_executions(created_at);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_modal_call_id ON public.workflow_executions(modal_call_id);

-- Add RLS policies
ALTER TABLE public.workflow_executions ENABLE ROW LEVEL SECURITY;

-- Policy: Clients can only see their own executions
CREATE POLICY "Clients can see own executions" ON public.workflow_executions
    FOR SELECT USING (client_id = current_setting('request.jwt.claims', true)::json->>'client_id');

-- Policy: System can insert executions
CREATE POLICY "System can insert executions" ON public.workflow_executions
    FOR INSERT WITH CHECK (true);

-- Policy: System can update executions
CREATE POLICY "System can update executions" ON public.workflow_executions
    FOR UPDATE USING (true);

-- Add trigger for updated_at
CREATE TRIGGER update_workflow_executions_updated_at 
    BEFORE UPDATE ON public.workflow_executions 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function to update workflow statistics after execution
CREATE OR REPLACE FUNCTION update_workflow_stats()
RETURNS TRIGGER AS $$
BEGIN
    -- Only update stats when status changes to completed or failed
    IF NEW.status IN ('completed', 'failed') AND OLD.status NOT IN ('completed', 'failed') THEN
        IF NEW.status = 'completed' THEN
            UPDATE public.deployed_workflows 
            SET 
                successful_runs = successful_runs + 1,
                total_executions = total_executions + 1,
                last_successful_execution = NEW.completed_at,
                updated_at = now()
            WHERE id = NEW.workflow_id;
        ELSIF NEW.status = 'failed' THEN
            UPDATE public.deployed_workflows 
            SET 
                failed_runs = failed_runs + 1,
                total_executions = total_executions + 1,
                last_failed_execution = NEW.completed_at,
                updated_at = now()
            WHERE id = NEW.workflow_id;
        END IF;
    END IF;
    
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Add trigger to update workflow stats
CREATE TRIGGER update_workflow_stats_trigger
    AFTER UPDATE ON public.workflow_executions
    FOR EACH ROW EXECUTE FUNCTION update_workflow_stats();

-- Add comments for documentation
COMMENT ON TABLE public.workflow_executions IS 'Tracks individual workflow execution requests and results';
COMMENT ON COLUMN public.workflow_executions.client_id IS 'API key or unique identifier for the requesting client';
COMMENT ON COLUMN public.workflow_executions.execution_params IS 'Input parameters provided by client for this execution';
COMMENT ON COLUMN public.workflow_executions.modal_call_id IS 'Modal function call ID for tracking remote execution';
COMMENT ON COLUMN public.workflow_executions.priority IS 'Execution priority queue position (1=highest, 10=lowest)';
COMMENT ON COLUMN public.workflow_executions.compute_cost_cents IS 'Execution cost in cents for billing purposes';
