-- Migration: Add organization-based machine access control
-- Created: 2026-01-14
-- Description: Allows limiting remote machines to specific organizations

-- =============================================================================
-- Table: machine_organization_assignments
-- Manages which organizations have access to which machines
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.machine_organization_assignments (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    machine_id integer NOT NULL REFERENCES public.remote_machines(id) ON DELETE CASCADE,
    organization_id text NOT NULL, -- Clerk organization ID
    assigned_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    assigned_at timestamp with time zone DEFAULT now(),

    -- Ensure unique assignment per machine-organization pair
    UNIQUE(machine_id, organization_id)
);

-- Add is_global flag to remote_machines table
-- If true, machine is available to all organizations (default behavior)
-- If false, machine is only available to organizations in machine_organization_assignments
ALTER TABLE public.remote_machines
ADD COLUMN IF NOT EXISTS is_global boolean DEFAULT true;

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_machine_org_assignments_machine ON public.machine_organization_assignments(machine_id);
CREATE INDEX IF NOT EXISTS idx_machine_org_assignments_org ON public.machine_organization_assignments(organization_id);
CREATE INDEX IF NOT EXISTS idx_remote_machines_is_global ON public.remote_machines(is_global);

-- =============================================================================
-- Functions for machine organization access
-- =============================================================================

-- Function to check if an organization has access to a machine
CREATE OR REPLACE FUNCTION check_machine_access(
    p_machine_id integer,
    p_organization_id text
) RETURNS boolean AS $$
DECLARE
    v_has_access boolean;
    v_is_global boolean;
BEGIN
    -- Check if machine is global
    SELECT is_global INTO v_is_global
    FROM public.remote_machines
    WHERE id = p_machine_id;

    -- If machine is global, everyone has access
    IF v_is_global THEN
        RETURN true;
    END IF;

    -- Otherwise, check if organization has explicit access
    SELECT EXISTS(
        SELECT 1 FROM public.machine_organization_assignments
        WHERE machine_id = p_machine_id
        AND organization_id = p_organization_id
    ) INTO v_has_access;

    RETURN v_has_access;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to assign machine to an organization
CREATE OR REPLACE FUNCTION assign_machine_to_org(
    p_machine_id integer,
    p_organization_id text,
    p_assigned_by uuid DEFAULT auth.uid()
) RETURNS void AS $$
BEGIN
    INSERT INTO public.machine_organization_assignments (
        machine_id,
        organization_id,
        assigned_by,
        assigned_at
    ) VALUES (
        p_machine_id,
        p_organization_id,
        p_assigned_by,
        now()
    )
    ON CONFLICT (machine_id, organization_id) DO NOTHING;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to remove machine from an organization
CREATE OR REPLACE FUNCTION remove_machine_from_org(
    p_machine_id integer,
    p_organization_id text
) RETURNS void AS $$
BEGIN
    DELETE FROM public.machine_organization_assignments
    WHERE machine_id = p_machine_id
    AND organization_id = p_organization_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get all organizations assigned to a machine
CREATE OR REPLACE FUNCTION get_machine_organizations(
    p_machine_id integer
) RETURNS TABLE(organization_id text, assigned_at timestamp with time zone) AS $$
BEGIN
    RETURN QUERY
    SELECT moa.organization_id, moa.assigned_at
    FROM public.machine_organization_assignments moa
    WHERE moa.machine_id = p_machine_id
    ORDER BY moa.assigned_at;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- RLS Policies
-- =============================================================================

-- Enable RLS on the new table
ALTER TABLE public.machine_organization_assignments ENABLE ROW LEVEL SECURITY;

-- Users can read machine organization assignments
CREATE POLICY "Users can read machine org assignments" ON public.machine_organization_assignments
    FOR SELECT USING (true);

-- Authenticated users can manage assignments (will be restricted to admins in app layer)
CREATE POLICY "Authenticated users can manage machine org assignments" ON public.machine_organization_assignments
    FOR ALL WITH CHECK (auth.uid() IS NOT NULL);

-- =============================================================================
-- Comments for documentation
-- =============================================================================

COMMENT ON TABLE public.machine_organization_assignments IS 'Manages which organizations have access to which remote machines';
COMMENT ON COLUMN public.remote_machines.is_global IS 'If true, machine is available to all organizations; if false, only to assigned organizations';
COMMENT ON FUNCTION check_machine_access(integer, text) IS 'Checks if an organization has access to a specific machine';
COMMENT ON FUNCTION assign_machine_to_org(integer, text, uuid) IS 'Assigns a machine to an organization';
COMMENT ON FUNCTION remove_machine_from_org(integer, text) IS 'Removes machine access from an organization';
COMMENT ON FUNCTION get_machine_organizations(integer) IS 'Returns all organizations assigned to a machine';
