-- Migration: Create workflow chat sessions table
-- Created: 2025-11-28
-- Description: Stores chat session history per user per workflow for the desktop app

-- Create workflow chat sessions table
CREATE TABLE IF NOT EXISTS public.workflow_chat_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Foreign keys
  workflow_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,  -- Clerk user ID

  -- Session reference
  redis_session_id TEXT NOT NULL,  -- UUID stored in Redis (ai-session:{id})

  -- Chat metadata
  title TEXT,  -- Optional title (e.g., first message preview)
  message_count INTEGER DEFAULT 0,

  -- Local copy of messages for quick loading (synced from localStorage)
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add foreign key constraint for workflow
ALTER TABLE public.workflow_chat_sessions
  ADD CONSTRAINT fk_workflow
    FOREIGN KEY (workflow_id)
    REFERENCES public.low_level_workflows(id)
    ON DELETE CASCADE;

-- Indexes for performance
CREATE INDEX idx_chat_sessions_workflow_id ON public.workflow_chat_sessions(workflow_id);
CREATE INDEX idx_chat_sessions_user_id ON public.workflow_chat_sessions(user_id);
CREATE INDEX idx_chat_sessions_user_workflow ON public.workflow_chat_sessions(user_id, workflow_id);
CREATE INDEX idx_chat_sessions_updated_at ON public.workflow_chat_sessions(updated_at DESC);
CREATE INDEX idx_chat_sessions_redis_id ON public.workflow_chat_sessions(redis_session_id);

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_chat_session_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_update_chat_session_timestamp
  BEFORE UPDATE ON public.workflow_chat_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_chat_session_timestamp();

-- RLS Policies (Row Level Security)
ALTER TABLE public.workflow_chat_sessions ENABLE ROW LEVEL SECURITY;

-- Service role can manage all sessions (for API endpoints)
CREATE POLICY "Service role can manage all chat sessions"
  ON public.workflow_chat_sessions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE public.workflow_chat_sessions IS 'Stores chat session history per user per workflow for the desktop app';
COMMENT ON COLUMN public.workflow_chat_sessions.workflow_id IS 'Reference to low_level_workflows table';
COMMENT ON COLUMN public.workflow_chat_sessions.user_id IS 'Clerk user ID';
COMMENT ON COLUMN public.workflow_chat_sessions.redis_session_id IS 'UUID of the session stored in Redis (ai-session:{id})';
COMMENT ON COLUMN public.workflow_chat_sessions.title IS 'Optional title for the chat session';
COMMENT ON COLUMN public.workflow_chat_sessions.message_count IS 'Number of messages in the conversation';
COMMENT ON COLUMN public.workflow_chat_sessions.messages IS 'JSONB array of conversation messages';
