-- Migration: Create execution Q&A conversations table
-- Created: 2025-10-20
-- Description: Stores persistent Q&A conversation history for workflow executions

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create execution Q&A conversations table
CREATE TABLE IF NOT EXISTS public.execution_qa_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Foreign keys
  execution_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,

  -- Conversation data
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  -- Ensure one conversation per user per execution
  CONSTRAINT unique_user_execution UNIQUE(execution_id, user_id)
);

-- Add foreign key constraints
ALTER TABLE public.execution_qa_conversations
  ADD CONSTRAINT fk_execution
    FOREIGN KEY (execution_id)
    REFERENCES public.workflow_executions(id)
    ON DELETE CASCADE;

ALTER TABLE public.execution_qa_conversations
  ADD CONSTRAINT fk_user
    FOREIGN KEY (user_id)
    REFERENCES public.mediar_users(user_id)
    ON DELETE CASCADE;

-- Indexes for performance
CREATE INDEX idx_qa_conversations_execution_id ON public.execution_qa_conversations(execution_id);
CREATE INDEX idx_qa_conversations_user_id ON public.execution_qa_conversations(user_id);
CREATE INDEX idx_qa_conversations_updated_at ON public.execution_qa_conversations(updated_at DESC);

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_qa_conversation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_update_qa_conversation_timestamp
  BEFORE UPDATE ON public.execution_qa_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_qa_conversation_timestamp();

-- RLS Policies (Row Level Security)
ALTER TABLE public.execution_qa_conversations ENABLE ROW LEVEL SECURITY;

-- Users can read their own conversations
-- Note: user_id in this table is the Clerk user ID (TEXT)
CREATE POLICY "Users can read own qa conversations"
  ON public.execution_qa_conversations
  FOR SELECT
  USING (user_id = (current_setting('request.jwt.claims', true)::json->>'sub')::text);

-- Users can insert their own conversations
CREATE POLICY "Users can insert own qa conversations"
  ON public.execution_qa_conversations
  FOR INSERT
  WITH CHECK (user_id = (current_setting('request.jwt.claims', true)::json->>'sub')::text);

-- Users can update their own conversations
CREATE POLICY "Users can update own qa conversations"
  ON public.execution_qa_conversations
  FOR UPDATE
  USING (user_id = (current_setting('request.jwt.claims', true)::json->>'sub')::text);

-- Users can delete their own conversations
CREATE POLICY "Users can delete own qa conversations"
  ON public.execution_qa_conversations
  FOR DELETE
  USING (user_id = (current_setting('request.jwt.claims', true)::json->>'sub')::text);

-- Service role can manage all conversations (for API endpoints)
CREATE POLICY "Service role can manage all qa conversations"
  ON public.execution_qa_conversations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE public.execution_qa_conversations IS 'Stores Q&A conversation history between users and AI assistant about workflow executions';
COMMENT ON COLUMN public.execution_qa_conversations.execution_id IS 'Reference to workflow_executions table, CASCADE deletes when execution is deleted';
COMMENT ON COLUMN public.execution_qa_conversations.user_id IS 'Reference to mediar_users table, CASCADE deletes when user is deleted';
COMMENT ON COLUMN public.execution_qa_conversations.messages IS 'JSONB array of conversation messages with structure: [{id, role, content, timestamp}]';
COMMENT ON CONSTRAINT unique_user_execution ON public.execution_qa_conversations IS 'Ensures one conversation per user per execution';
