-- Add workflow component tables for proper ID-based relationships
-- This enables the timeline mapping to use IDs instead of text matching

-- =============================================================================
-- Workflow Steps Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.workflow_steps (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_template_id bigint REFERENCES public.low_level_workflows(id) ON DELETE CASCADE,
    step_name text NOT NULL,
    step_order integer DEFAULT 0,
    step_description text,
    user_id uuid NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT unique_workflow_step UNIQUE(workflow_template_id, step_name)
);

-- =============================================================================
-- Workflow Substeps Table  
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.workflow_substeps (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_step_id bigint REFERENCES public.workflow_steps(id) ON DELETE CASCADE,
    substep_name text NOT NULL,
    substep_order integer DEFAULT 0,
    substep_description text,
    inputs text[] DEFAULT '{}',
    outputs text[] DEFAULT '{}',
    business_logic text[] DEFAULT '{}',
    user_id uuid NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT unique_workflow_substep UNIQUE(workflow_step_id, substep_name)
);

-- =============================================================================
-- Update timeline_event_annotations to use step/substep IDs
-- =============================================================================
-- Add new ID columns (nullable for migration compatibility)
ALTER TABLE "public"."timeline_event_annotations" 
ADD COLUMN IF NOT EXISTS "workflow_step_id" bigint,
ADD COLUMN IF NOT EXISTS "workflow_substep_id" bigint;

-- Add foreign key constraints
ALTER TABLE "public"."timeline_event_annotations" 
ADD CONSTRAINT "timeline_event_annotations_workflow_step_id_fkey" 
FOREIGN KEY (workflow_step_id) REFERENCES public.workflow_steps(id) ON DELETE SET NULL;

ALTER TABLE "public"."timeline_event_annotations" 
ADD CONSTRAINT "timeline_event_annotations_workflow_substep_id_fkey" 
FOREIGN KEY (workflow_substep_id) REFERENCES public.workflow_substeps(id) ON DELETE SET NULL;

-- =============================================================================
-- Indexes for Performance
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_workflow_steps_template ON workflow_steps(workflow_template_id);
CREATE INDEX IF NOT EXISTS idx_workflow_steps_user ON workflow_steps(user_id);

CREATE INDEX IF NOT EXISTS idx_workflow_substeps_step ON workflow_substeps(workflow_step_id);
CREATE INDEX IF NOT EXISTS idx_workflow_substeps_user ON workflow_substeps(user_id);

CREATE INDEX IF NOT EXISTS idx_timeline_annotations_step_id ON timeline_event_annotations(workflow_step_id);
CREATE INDEX IF NOT EXISTS idx_timeline_annotations_substep_id ON timeline_event_annotations(workflow_substep_id);

-- =============================================================================
-- Comments for Documentation
-- =============================================================================
COMMENT ON TABLE workflow_steps IS 'Individual steps within workflows with proper ID references';
COMMENT ON TABLE workflow_substeps IS 'Granular substeps within workflow steps with inputs/outputs/business logic';
COMMENT ON COLUMN timeline_event_annotations.workflow_step_id IS 'ID reference to workflow_steps table (replaces step_name)';
COMMENT ON COLUMN timeline_event_annotations.workflow_substep_id IS 'ID reference to workflow_substeps table (replaces substep_name)'; 