-- This is a consolidated migration file to set up the entire database from a clean slate.
-- It combines all necessary table creations and logic into a single, ordered script.

-- =============================================================================
-- Table: mediar_users
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.mediar_users (
  id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  clerk_user_id text NOT NULL UNIQUE,
  email text,
  role text DEFAULT 'viewer'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- =============================================================================
-- Table: low_level_workflow_analyses
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_workflow_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.mediar_users(id) ON DELETE CASCADE,
  session_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  client_timestamp TIMESTAMPTZ,
  llm_structured_output JSONB,
  context_metadata JSONB
);

-- =============================================================================
-- Table: synthesis_sessions
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.synthesis_sessions (
    id bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id uuid NOT NULL,
    session_state jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- =============================================================================
-- Table: low_level_workflows
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_workflows (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    title text,
    inputs text[],
    outputs text[],
    steps text[],
    business_logic text[],
    created_at timestamp with time zone DEFAULT now(),
    chat_history jsonb,
    workflow_context jsonb,
    synthesis_session_id bigint REFERENCES public.synthesis_sessions(id) ON DELETE SET NULL
);

-- =============================================================================
-- Table: low_level_workflow_labeling
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_workflow_labeling (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid,
    low_level_workflow_analysis_id bigint UNIQUE REFERENCES public.low_level_workflow_analyses(id) ON DELETE CASCADE,
    suggested_labels text[],
    selected_labels text[],
    created_at timestamp with time zone DEFAULT now()
);

-- =============================================================================
-- Table: llm_traces
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.llm_traces (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    analysis_id BIGINT REFERENCES public.low_level_workflow_analyses(id) ON DELETE SET NULL,
    user_id TEXT,
    session_id TEXT,
    call_type TEXT NOT NULL,
    model_name TEXT NOT NULL,
    provider TEXT DEFAULT 'google',
    raw_input JSONB NOT NULL,
    raw_output JSONB,
    structured_output JSONB,
    processing_time_ms INTEGER,
    tokens_input INTEGER,
    tokens_output INTEGER,
    tokens_total INTEGER,
    cost_usd DECIMAL(10, 6),
    status TEXT DEFAULT 'pending',
    error_message TEXT,
    request_id TEXT,
    client_timestamp TIMESTAMPTZ,
    response_timestamp TIMESTAMPTZ,
    metadata JSONB
);

-- =============================================================================
-- Table: low_level_events
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  session_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  payload JSONB
);

-- =============================================================================
-- Table: user_activity_data
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.user_activity_data (
  id UUID PRIMARY KEY,
  user_id UUID,
  session_id TEXT,
  client_timestamp TIMESTAMPTZ,
  source TEXT,
  payload JSONB
);

-- =============================================================================
-- Table: session_metadata
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.session_metadata (
  session_id TEXT PRIMARY KEY,
  user_id UUID,
  event_count INTEGER DEFAULT 0,
  processed_event_count INTEGER DEFAULT 0,
  total_ui_steps INTEGER DEFAULT 0,
  total_workflow_analyses INTEGER DEFAULT 0,
  distinct_workflows_created INTEGER DEFAULT 0,
  total_labeled_steps INTEGER DEFAULT 0,
  human_labeled_steps INTEGER DEFAULT 0,
  first_event_timestamp TIMESTAMPTZ,
  last_event_timestamp TIMESTAMPTZ,
  duration_seconds INTEGER DEFAULT 0,
  session_type TEXT
);

-- =============================================================================
-- Table: low_level_datasets
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_datasets (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES public.mediar_users(id) ON DELETE SET NULL,
    dataset_type TEXT NOT NULL,
    low_level_workflow_analysis_id BIGINT REFERENCES public.low_level_workflow_analyses(id) ON DELETE CASCADE,
    generated_output TEXT,
    feedback TEXT,
    feedback_reason TEXT,
    CONSTRAINT unique_feedback_entry UNIQUE (dataset_type, low_level_workflow_analysis_id)
);
COMMENT ON TABLE public.low_level_datasets IS 'Stores datasets for analysis, such as user feedback on generated content.';

-- =============================================================================
-- Table: workflow_analysis_jobs
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.workflow_analysis_jobs (
    id bigint NOT NULL PRIMARY KEY DEFAULT nextval('workflow_analysis_jobs_id_seq'::regclass),
    user_id uuid NOT NULL,
    event_id bigint NOT NULL,
    status text DEFAULT 'pending'::text,
    payload jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- =============================================================================
-- Function: Incremental Session Metadata Updates
-- =============================================================================
CREATE OR REPLACE FUNCTION public.update_session_metadata_on_event()
RETURNS TRIGGER AS $$
DECLARE
    v_session_id TEXT;
    v_user_id TEXT;
    v_event_timestamp TIMESTAMPTZ;
    v_session_type TEXT;
BEGIN
    IF TG_TABLE_NAME = 'low_level_events' THEN
        v_session_id := NEW.session_id;
        v_user_id := NEW.user_id;
        v_event_timestamp := NEW.created_at;
        v_session_type := 'low-level';
    ELSIF TG_TABLE_NAME = 'user_activity_data' THEN
        v_session_id := NEW.session_id;
        v_user_id := NEW.user_id;
        v_event_timestamp := NEW.client_timestamp;
        v_session_type := COALESCE(NEW.source, 'web');
    END IF;

    IF v_session_id IS NULL THEN RETURN NULL; END IF;

    INSERT INTO public.session_metadata (session_id, user_id, event_count, first_event_timestamp, last_event_timestamp, duration_seconds, session_type)
    VALUES (v_session_id, v_user_id, 1, v_event_timestamp, v_event_timestamp, 0, v_session_type)
    ON CONFLICT (session_id) DO UPDATE SET
        event_count = session_metadata.event_count + 1,
        last_event_timestamp = v_event_timestamp,
        duration_seconds = EXTRACT(EPOCH FROM (v_event_timestamp - session_metadata.first_event_timestamp)),
        session_type = CASE WHEN session_metadata.session_type != v_session_type THEN 'mixed' ELSE v_session_type END;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- Triggers for Incremental Updates
-- =============================================================================
CREATE TRIGGER handle_new_low_level_event
AFTER INSERT ON public.low_level_events
FOR EACH ROW EXECUTE FUNCTION public.update_session_metadata_on_event();

CREATE TRIGGER handle_new_user_activity_event  
AFTER INSERT ON public.user_activity_data
FOR EACH ROW EXECUTE FUNCTION public.update_session_metadata_on_event();

