-- This is a consolidated migration file to set up the entire database from a clean slate.
-- It combines all necessary table creations and logic into a single, ordered script.

-- =============================================================================
-- Table: users
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.users (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  clerk_user_id text NOT NULL,
  email text,
  role text DEFAULT 'viewer'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_clerk_user_id_key UNIQUE (clerk_user_id)
);
COMMENT ON TABLE public.users IS 'Stores user information for dashboard viewers, linked to Clerk accounts.';
COMMENT ON COLUMN public.users.clerk_user_id IS 'The user ID from the Clerk authentication service.';
COMMENT ON COLUMN public.users.role IS 'The access role of the user (e.g., admin, viewer).';

-- =============================================================================
-- Table: low_level_workflow_analyses
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_workflow_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  session_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  client_timestamp TIMESTAMPTZ,
  llm_structured_output JSONB,
  context_metadata JSONB
);
ALTER TABLE public.low_level_workflow_analyses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow user to view their own analyses" ON public.low_level_workflow_analyses FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Allow user to insert their own analyses" ON public.low_level_workflow_analyses FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- =============================================================================
-- Table: llm_traces
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.llm_traces (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    analysis_id BIGINT REFERENCES public.low_level_workflow_analyses(id) ON DELETE SET NULL,
    user_id TEXT,
    session_id TEXT,
    call_type TEXT NOT NULL,
    model_name TEXT NOT NULL,
    provider TEXT DEFAULT 'google',
    raw_input JSONB NOT NULL,
    raw_output JSONB,
    structured_output JSONB,
    processing_time_ms INTEGER,
    tokens_input INTEGER,
    tokens_output INTEGER,
    tokens_total INTEGER,
    cost_usd DECIMAL(10, 6),
    status TEXT DEFAULT 'pending',
    error_message TEXT,
    request_id TEXT,
    client_timestamp TIMESTAMPTZ,
    response_timestamp TIMESTAMPTZ,
    metadata JSONB
);

-- =============================================================================
-- Table: low_level_events
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  session_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  payload JSONB
);

-- =============================================================================
-- Table: user_activity_data
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.user_activity_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  session_id TEXT,
  client_timestamp TIMESTAMPTZ,
  source TEXT,
  payload JSONB
);

-- =============================================================================
-- Table: session_metadata
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.session_metadata (
  session_id TEXT PRIMARY KEY,
  user_id UUID,
  event_count INTEGER DEFAULT 0,
  processed_event_count INTEGER DEFAULT 0,
  total_ui_steps INTEGER DEFAULT 0,
  total_workflow_analyses INTEGER DEFAULT 0,
  distinct_workflows_created INTEGER DEFAULT 0,
  total_labeled_steps INTEGER DEFAULT 0,
  human_labeled_steps INTEGER DEFAULT 0,
  first_event_timestamp TIMESTAMPTZ,
  last_event_timestamp TIMESTAMPTZ,
  duration_seconds INTEGER DEFAULT 0,
  session_type TEXT
);

-- =============================================================================
-- Table: low_level_datasets
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.low_level_datasets (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    dataset_type TEXT NOT NULL,
    low_level_workflow_analysis_id BIGINT REFERENCES public.low_level_workflow_analyses(id) ON DELETE CASCADE,
    generated_output TEXT,
    feedback TEXT,
    feedback_reason TEXT,
    CONSTRAINT unique_feedback_entry UNIQUE (dataset_type, low_level_workflow_analysis_id)
);
COMMENT ON TABLE public.low_level_datasets IS 'Stores datasets for analysis, such as user feedback on generated content.';

-- =============================================================================
-- Function: Incremental Session Metadata Updates
-- =============================================================================
CREATE OR REPLACE FUNCTION public.update_session_metadata_on_event()
RETURNS TRIGGER AS $$
DECLARE
    v_session_id TEXT;
    v_user_id TEXT;
    v_event_timestamp TIMESTAMPTZ;
    v_session_type TEXT;
BEGIN
    IF TG_TABLE_NAME = 'low_level_events' THEN
        v_session_id := NEW.session_id;
        v_user_id := NEW.user_id;
        v_event_timestamp := NEW.created_at;
        v_session_type := 'low-level';
    ELSIF TG_TABLE_NAME = 'user_activity_data' THEN
        v_session_id := NEW.session_id;
        v_user_id := NEW.user_id;
        v_event_timestamp := NEW.client_timestamp;
        v_session_type := COALESCE(NEW.source, 'web');
    END IF;

    IF v_session_id IS NULL THEN RETURN NULL; END IF;

    INSERT INTO public.session_metadata (session_id, user_id, event_count, first_event_timestamp, last_event_timestamp, duration_seconds, session_type)
    VALUES (v_session_id, v_user_id, 1, v_event_timestamp, v_event_timestamp, 0, v_session_type)
    ON CONFLICT (session_id) DO UPDATE SET
        event_count = session_metadata.event_count + 1,
        last_event_timestamp = v_event_timestamp,
        duration_seconds = EXTRACT(EPOCH FROM (v_event_timestamp - session_metadata.first_event_timestamp)),
        session_type = CASE WHEN session_metadata.session_type != v_session_type THEN 'mixed' ELSE v_session_type END;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- Triggers for Incremental Updates
-- =============================================================================
CREATE TRIGGER handle_new_low_level_event
AFTER INSERT ON public.low_level_events
FOR EACH ROW EXECUTE FUNCTION public.update_session_metadata_on_event();

CREATE TRIGGER handle_new_user_activity_event  
AFTER INSERT ON public.user_activity_data
FOR EACH ROW EXECUTE FUNCTION public.update_session_metadata_on_event();

