-- Migration: Create user message analysis conversations table
-- Created: 2026-01-19
-- Description: Stores persistent conversation history for admin user message analysis

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create user message analysis conversations table
CREATE TABLE IF NOT EXISTS public.user_message_analysis_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Target user being analyzed (TEXT - Clerk user ID)
  target_user_id TEXT NOT NULL,

  -- Admin performing the analysis (TEXT - Clerk user ID)
  admin_user_id TEXT NOT NULL,

  -- Conversation data
  messages JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  -- Ensure one conversation per admin-user pair
  CONSTRAINT unique_admin_target_user UNIQUE(target_user_id, admin_user_id)
);

-- Add foreign key constraints
ALTER TABLE public.user_message_analysis_conversations
  ADD CONSTRAINT fk_target_user
    FOREIGN KEY (target_user_id)
    REFERENCES public.mediar_users(user_id)
    ON DELETE CASCADE;

ALTER TABLE public.user_message_analysis_conversations
  ADD CONSTRAINT fk_admin_user
    FOREIGN KEY (admin_user_id)
    REFERENCES public.mediar_users(user_id)
    ON DELETE CASCADE;

-- Indexes for performance
CREATE INDEX idx_user_msg_analysis_target_user_id ON public.user_message_analysis_conversations(target_user_id);
CREATE INDEX idx_user_msg_analysis_admin_user_id ON public.user_message_analysis_conversations(admin_user_id);
CREATE INDEX idx_user_msg_analysis_updated_at ON public.user_message_analysis_conversations(updated_at DESC);

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_user_msg_analysis_conversation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_update_user_msg_analysis_conversation_timestamp
  BEFORE UPDATE ON public.user_message_analysis_conversations
  FOR EACH ROW
  EXECUTE FUNCTION update_user_msg_analysis_conversation_timestamp();

-- RLS Policies (Row Level Security)
-- This is an admin-only table, accessed via service role from API endpoints
ALTER TABLE public.user_message_analysis_conversations ENABLE ROW LEVEL SECURITY;

-- Service role can manage all conversations (for admin API endpoints)
CREATE POLICY "Service role can manage all user msg analysis conversations"
  ON public.user_message_analysis_conversations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE public.user_message_analysis_conversations IS 'Stores admin conversation history for analyzing user messages';
COMMENT ON COLUMN public.user_message_analysis_conversations.target_user_id IS 'The user whose messages are being analyzed';
COMMENT ON COLUMN public.user_message_analysis_conversations.admin_user_id IS 'The admin performing the analysis';
COMMENT ON COLUMN public.user_message_analysis_conversations.messages IS 'JSONB array of conversation messages with structure: [{id, role, content, timestamp}]';
COMMENT ON CONSTRAINT unique_admin_target_user ON public.user_message_analysis_conversations IS 'Ensures one conversation per admin per target user';
