-- Migration: Add organization support for workflows
-- Created: 2026-01-10
-- Description: Adds organization ownership and access control for workflows, allowing Mediar to manage access

-- =============================================================================
-- Table: workflow_organization_access
-- This table manages which organizations have access to which workflows
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.workflow_organization_access (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_id bigint NOT NULL REFERENCES public.deployed_workflows(id) ON DELETE CASCADE,
    organization_id text NOT NULL, -- Clerk organization ID
    access_level text DEFAULT 'read' CHECK (access_level IN ('read', 'write', 'admin')),
    granted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    granted_at timestamp with time zone DEFAULT now(),

    -- Ensure unique access per workflow-organization pair
    UNIQUE(workflow_id, organization_id)
);

-- Add organization_id to deployed_workflows table for primary ownership
ALTER TABLE public.deployed_workflows
ADD COLUMN IF NOT EXISTS organization_id text,
ADD COLUMN IF NOT EXISTS is_shared boolean DEFAULT false;

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_workflow_org_access_workflow ON public.workflow_organization_access(workflow_id);
CREATE INDEX IF NOT EXISTS idx_workflow_org_access_org ON public.workflow_organization_access(organization_id);
CREATE INDEX IF NOT EXISTS idx_deployed_workflows_org ON public.deployed_workflows(organization_id);

-- =============================================================================
-- Table: workflow_execution_stats_by_org
-- Track execution statistics per organization
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.workflow_execution_stats_by_org (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_id bigint NOT NULL REFERENCES public.deployed_workflows(id) ON DELETE CASCADE,
    organization_id text NOT NULL,
    successful_runs integer DEFAULT 0,
    failed_runs integer DEFAULT 0,
    total_executions integer DEFAULT 0,
    last_execution_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),

    UNIQUE(workflow_id, organization_id)
);

CREATE INDEX IF NOT EXISTS idx_workflow_exec_stats_org ON public.workflow_execution_stats_by_org(organization_id);

-- =============================================================================
-- Update RLS Policies
-- =============================================================================

-- Drop existing policies that need modification
DROP POLICY IF EXISTS "Users can read active workflows" ON public.deployed_workflows;
DROP POLICY IF EXISTS "Authenticated users can create workflows" ON public.deployed_workflows;
DROP POLICY IF EXISTS "Users can update own workflows" ON public.deployed_workflows;
DROP POLICY IF EXISTS "Users can delete own workflows" ON public.deployed_workflows;

-- Create new organization-aware policies
-- Note: These policies will need to be enforced in the application layer since Supabase RLS
-- doesn't have direct access to Clerk organization data

-- Policy: Users can read workflows their organization has access to
-- This will be enforced in the API layer by checking Clerk organization membership
CREATE POLICY "Organization members can read workflows" ON public.deployed_workflows
    FOR SELECT USING (
        status = 'active' AND (
            -- Check will be done in API layer
            auth.uid() IS NOT NULL
        )
    );

-- Policy: Users can create workflows for their organization
CREATE POLICY "Organization members can create workflows" ON public.deployed_workflows
    FOR INSERT WITH CHECK (
        auth.uid() IS NOT NULL
        -- Organization check in API layer
    );

-- Policy: Users can update workflows owned by their organization
CREATE POLICY "Organization members can update workflows" ON public.deployed_workflows
    FOR UPDATE USING (
        auth.uid() IS NOT NULL
        -- Organization check in API layer
    );

-- Policy: Only admins can delete workflows
CREATE POLICY "Organization admins can delete workflows" ON public.deployed_workflows
    FOR DELETE USING (
        auth.uid() IS NOT NULL
        -- Admin check in API layer
    );

-- =============================================================================
-- Functions for organization workflow access
-- =============================================================================

-- Function to check if an organization has access to a workflow
CREATE OR REPLACE FUNCTION check_workflow_access(
    p_workflow_id bigint,
    p_organization_id text
) RETURNS boolean AS $$
DECLARE
    v_has_access boolean;
BEGIN
    SELECT EXISTS(
        SELECT 1 FROM public.deployed_workflows w
        WHERE w.id = p_workflow_id
        AND (
            w.organization_id = p_organization_id OR
            EXISTS (
                SELECT 1 FROM public.workflow_organization_access woa
                WHERE woa.workflow_id = w.id
                AND woa.organization_id = p_organization_id
            )
        )
    ) INTO v_has_access;

    RETURN v_has_access;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to grant workflow access to an organization
CREATE OR REPLACE FUNCTION grant_workflow_access(
    p_workflow_id bigint,
    p_organization_id text,
    p_access_level text DEFAULT 'read',
    p_granted_by uuid DEFAULT auth.uid()
) RETURNS void AS $$
BEGIN
    INSERT INTO public.workflow_organization_access (
        workflow_id,
        organization_id,
        access_level,
        granted_by,
        granted_at
    ) VALUES (
        p_workflow_id,
        p_organization_id,
        p_access_level,
        p_granted_by,
        now()
    )
    ON CONFLICT (workflow_id, organization_id)
    DO UPDATE SET
        access_level = EXCLUDED.access_level,
        granted_by = EXCLUDED.granted_by,
        granted_at = EXCLUDED.granted_at;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to revoke workflow access from an organization
CREATE OR REPLACE FUNCTION revoke_workflow_access(
    p_workflow_id bigint,
    p_organization_id text
) RETURNS void AS $$
BEGIN
    DELETE FROM public.workflow_organization_access
    WHERE workflow_id = p_workflow_id
    AND organization_id = p_organization_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- Migrate existing workflows to Mediar organization
-- =============================================================================

-- Set all existing workflows to belong to Mediar organization
-- Replace these IDs with actual Mediar org IDs from Clerk
UPDATE public.deployed_workflows
SET organization_id = 'org_2yydAO45WOB4RaCE4F4BNUPtw9c'
WHERE organization_id IS NULL;

-- Add comments for documentation
COMMENT ON TABLE public.workflow_organization_access IS 'Manages which organizations have access to which workflows';
COMMENT ON COLUMN public.deployed_workflows.organization_id IS 'Primary organization that owns this workflow';
COMMENT ON COLUMN public.deployed_workflows.is_shared IS 'Whether this workflow is shared with other organizations';
COMMENT ON COLUMN public.workflow_organization_access.access_level IS 'Level of access: read (view/execute), write (edit), admin (delete/share)';